image: 'debian:stretch-backports'

before_script:
  - apt-get update
  # Runtime dependencies
  - apt-get -y install python3-django/stretch-backports
  - apt-get -y install python3-requests python3-django-jsonfield python3-django-captcha python3-debian python3-debianbts python3-apt python3-gpgme python3-yaml python3-bs4 python3-pyinotify
  # Test dependencies
  - apt-get -y install python3-coverage python3-selenium chromium-driver xvfb python3-pip
  # Dependencies to build docs
  - apt-get -y make python3-sphinx

flake8:
  script:
    - pip3 install --upgrade flake8  # Ensure we have the latest version
    - python3 -m flake8 django_email_accounts/ functional_tests/ distro_tracker/

unit-tests:
  script:
    - python3 -m coverage erase
    - python3 -m coverage run ./manage.py test django_email_accounts distro_tracker
    - python3 -m coverage report | sed -e 's/^TOTAL         /TOTAL COVERAGE/'
  coverage: '/TOTAL COVERAGE.* (\d+(?:\.\d+)?%)/'
  artifacts:
    paths:
      - .coverage
    expire_in: 6h

functional-tests:
  script:
    - xvfb-run python3 ./manage.py test functional_tests

pages:
  stage: deploy
  dependencies:  # To retrieve .coverage artifact
    - unit-tests
  script:
    - make -C docs html
    - mv docs/_build/html/ public/
    - python3 -m coverage html -d public/coverage
  artifacts:
    paths:
      - public
  only:
    - master
