image: 'debian:9'

before_script:
  - apt-get update
  - apt-get -y install make python3-sphinx python3-django python3-requests python3-django-jsonfield python3-django-captcha python3-debian python3-debianbts python3-apt python3-gpgme python3-yaml python3-bs4 python3-pyinotify python3-selenium chromium-driver

pages:
  script:
    - make -C docs html
    - mv docs/_build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
